name: Update Plugin Data

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  update-data:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      
      - name: Set up Python
        run: uv python install
      
      - name: Sync plugin metadata
        run: uv run sync
      
      - name: Get README files
        run: uv run get-readme
      
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "has_changes=true" >> $GITHUB_OUTPUT
      
      - name: Commit and push changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "chore: update plugin metadata and READMEs [automated]"
          git push
      
      - name: No changes detected
        if: steps.git-check.outputs.has_changes != 'true'
        run: echo "No changes to commit"